### ISSUE TITLE
Loved the article and this script looks great too.

### ISSUE THREAD

**Issue by obeid** [mikedrew/archOnX220#1]
I found your article here http://www.mikedrew.org/archlinux-on-x220/ and It was the only guiding light get arch going using UEFI boot. Thanks for writing a very specific article for the x220 (love that labtop, don't you?). Also was a nice surprise to find you are in North Carolina as well.

Cheers!

**Comment by mikedrew** [comment]
Thank you! I'm glad you found it useful!

**Comment by mikedrew** [comment]
I'm so glad the article and script were useful to you! The x220 really is
great. So far I haven't noticed any incompatibilities with arch and that
was my main reason for getting it. It's awesome we're both in the Triangle
area too!
